CREATE TABLE IF NOT EXISTS steamfake_jogos (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(150) NOT NULL,
  slug VARCHAR(160) NOT NULL,
  descricao TEXT NOT NULL,
  imagem VARCHAR(255) NOT NULL,
  plataforma VARCHAR(60) NOT NULL DEFAULT 'PC',
  genero VARCHAR(100) NOT NULL,
  avaliacao DECIMAL(2,1) NOT NULL DEFAULT 0.0,
  preco_original DECIMAL(10,2) NOT NULL,
  preco_atual DECIMAL(10,2) NOT NULL,
  desconto DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  promocao_status VARCHAR(80) NOT NULL DEFAULT 'Preço regular',
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id), UNIQUE KEY uq_steamfake_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO steamfake_jogos (id,nome,slug,descricao,imagem,plataforma,genero,avaliacao,preco_original,preco_atual,desconto,promocao_status) VALUES
(1,'Cyberpunk 2077','cyberpunk-2077','RPG de ação em mundo aberto ambientado em Night City.','assets/img/capa-padrao.svg','PC','RPG / Ação',4.7,199.90,99.95,50,'Oferta por tempo limitado'),
(2,'Red Dead Redemption 2','red-dead-redemption-2','Uma jornada épica pelo Velho Oeste americano.','assets/img/capa-padrao.svg','PC','Ação / Aventura',4.9,249.90,124.95,50,'Oferta por tempo limitado'),
(3,'Hogwarts Legacy','hogwarts-legacy','Explore Hogwarts no século XIX e aprenda feitiços.','assets/img/capa-padrao.svg','PC','RPG / Aventura',4.6,249.90,124.95,50,'Oferta por tempo limitado'),
(4,'Forza Horizon 5','forza-horizon-5','Corridas pelas paisagens vibrantes do México.','assets/img/capa-padrao.svg','PC','Corrida',4.8,249.90,149.94,40,'Oferta ativa'),
(5,'Elden Ring','elden-ring','Fantasia sombria com exploração livre e combates intensos.','assets/img/capa-padrao.svg','PC','RPG / Soulslike',4.9,229.90,160.93,30,'Oferta ativa'),
(6,'Baldur’s Gate 3','baldurs-gate-3','RPG baseado em escolhas, dados e consequências.','assets/img/capa-padrao.svg','PC','RPG / Estratégia',4.9,199.90,139.93,30,'Oferta ativa'),
(7,'Minecraft','minecraft','Construa, explore e sobreviva em um universo de blocos.','assets/img/capa-padrao.svg','PC','Sandbox / Aventura',4.8,119.90,119.90,0,'Preço regular'),
(8,'The Witcher 3: Wild Hunt','the-witcher-3-wild-hunt','Geralt de Rívia rastreia monstros em um continente em guerra.','assets/img/capa-padrao.svg','PC','RPG / Ação',4.9,149.90,44.97,70,'Oferta relâmpago'),
(9,'Grand Theft Auto V','grand-theft-auto-v','Três criminosos se unem em golpes na cidade de Los Santos.','assets/img/capa-padrao.svg','PC','Ação / Mundo aberto',4.7,99.90,24.97,75,'Oferta relâmpago'),
(10,'Hades','hades','Desafie o deus dos mortos em uma fuga pelo submundo.','assets/img/capa-padrao.svg','PC','Roguelike / Ação',4.9,89.90,44.95,50,'Oferta ativa'),
(11,'Hollow Knight','hollow-knight','Desbrave um reino subterrâneo repleto de segredos.','assets/img/capa-padrao.svg','PC','Metroidvania',4.8,57.90,28.95,50,'Oferta ativa'),
(12,'Dead Cells','dead-cells','Roguelite de ação com combate veloz e exploração ramificada.','assets/img/capa-padrao.svg','PC','Roguelite / Ação',4.7,59.90,35.94,40,'Oferta ativa'),
(13,'Stardew Valley','stardew-valley','Cultive sua fazenda, faça amizades e descubra o vale.','assets/img/capa-padrao.svg','PC','Simulação / RPG',4.9,39.90,19.95,50,'Oferta ativa'),
(14,'Resident Evil 4','resident-evil-4','Leon enfrenta uma missão de resgate em uma vila isolada.','assets/img/capa-padrao.svg','PC','Terror / Ação',4.8,249.90,174.93,30,'Oferta ativa'),
(15,'Street Fighter 6','street-fighter-6','A nova geração dos jogos de luta.','assets/img/capa-padrao.svg','PC','Luta',4.6,249.90,174.93,30,'Oferta ativa'),
(16,'Bioshock Infinite','bioshock-infinite','Uma aventura de ficção científica na cidade aérea de Columbia.','assets/img/capa-padrao.svg','PC','FPS / Narrativa',4.6,79.90,15.98,80,'Oferta relâmpago'),
(17,'Portal 2','portal-2','Resolva quebra-cabeças com portais e muita ironia.','assets/img/capa-padrao.svg','PC','Puzzle / Cooperação',4.9,36.90,7.38,80,'Oferta relâmpago'),
(18,'The Sims 4','the-sims-4','Crie personagens, construa casas e conte novas histórias.','assets/img/capa-padrao.svg','PC','Simulação',4.3,99.90,49.95,50,'Oferta ativa'),
(19,'Terraria','terraria','Cave, lute, explore e construa em um mundo 2D.','assets/img/capa-padrao.svg','PC','Sandbox / Aventura',4.8,39.90,19.95,50,'Oferta ativa'),
(20,'Sekiro: Shadows Die Twice','sekiro-shadows-die-twice','Domine a espada de um shinobi no Japão Sengoku.','assets/img/capa-padrao.svg','PC','Ação / Soulslike',4.8,229.90,160.93,30,'Oferta ativa'),
(21,'Death Stranding','death-stranding','Reconecte uma América fragmentada.','assets/img/capa-padrao.svg','PC','Ação / Aventura',4.4,199.90,69.96,65,'Oferta relâmpago'),
(22,'No Man’s Sky','no-mans-sky','Explore um universo praticamente infinito.','assets/img/capa-padrao.svg','PC','Exploração / Sobrevivência',4.5,199.90,99.95,50,'Oferta ativa'),
(23,'Sea of Thieves','sea-of-thieves','Aventuras piratas em alto-mar com sua tripulação.','assets/img/capa-padrao.svg','PC','Ação / Multiplayer',4.4,149.90,74.95,50,'Oferta ativa'),
(24,'Cuphead','cuphead','Chefes desafiadores em animação clássica.','assets/img/capa-padrao.svg','PC','Ação / Plataforma',4.7,79.90,39.95,50,'Oferta ativa'),
(25,'Celeste','celeste','Ajude Madeline a escalar uma montanha.','assets/img/capa-padrao.svg','PC','Plataforma / Narrativa',4.9,59.90,29.95,50,'Oferta ativa'),
(26,'Control','control','Habilidades sobrenaturais em uma agência secreta.','assets/img/capa-padrao.svg','PC','Ação / Ficção científica',4.5,149.90,44.97,70,'Oferta relâmpago'),
(27,'Doom Eternal','doom-eternal','Destrua hordas demoníacas em combate explosivo.','assets/img/capa-padrao.svg','PC','FPS / Ação',4.8,199.90,99.95,50,'Oferta ativa'),
(28,'Final Fantasy VII Remake','final-fantasy-vii-remake','A releitura visualmente impressionante de Midgar.','assets/img/capa-padrao.svg','PC','RPG / Ação',4.6,349.90,244.93,30,'Oferta ativa'),
(29,'Batalha Estelar: Origens','batalha-estelar-origens','Comande uma frota rebelde em uma campanha tática.','assets/img/capa-padrao.svg','PC','Estratégia / Sci-Fi',4.2,79.90,39.95,50,'Oferta ativa'),
(30,'Neon Drift Racing','neon-drift-racing','Corridas arcade em pistas futuristas.','assets/img/capa-padrao.svg','PC','Corrida / Arcade',4.1,69.90,34.95,50,'Oferta ativa'),
(31,'Alan Wake 2','alan-wake-2','Dois protagonistas enfrentam uma história de terror psicológico que atravessa a fronteira entre ficção e realidade.','assets/img/capa-padrao.svg','PC','Terror / Aventura',4.7,249.90,174.93,30,'Oferta ativa')
ON DUPLICATE KEY UPDATE nome=VALUES(nome), preco_original=VALUES(preco_original), preco_atual=VALUES(preco_atual), desconto=VALUES(desconto), atualizado_em=CURRENT_TIMESTAMP;
