CREATE TABLE IF NOT EXISTS gogfake_precos (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    jogo_id INT UNSIGNED NOT NULL,
    nome VARCHAR(160) NOT NULL,
    slug VARCHAR(180) NOT NULL UNIQUE,
    plataforma VARCHAR(80) NOT NULL DEFAULT 'PC',
    preco_original DECIMAL(10,2) NOT NULL,
    preco_atual DECIMAL(10,2) NOT NULL,
    desconto TINYINT UNSIGNED NOT NULL DEFAULT 0,
    imagem VARCHAR(500) NOT NULL,
    url VARCHAR(255) NOT NULL,
    loja VARCHAR(30) NOT NULL DEFAULT 'GOGFake',
    genero VARCHAR(80) NOT NULL,
    descricao TEXT NOT NULL,
    avaliacao DECIMAL(3,1) NOT NULL DEFAULT 8.0,
    destaque VARCHAR(30) NOT NULL DEFAULT 'popular',
    data_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_gogfake_jogo_id (jogo_id),
    INDEX idx_gogfake_genero (genero),
    INDEX idx_gogfake_preco (preco_atual)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO gogfake_precos
(jogo_id,nome,slug,plataforma,preco_original,preco_atual,desconto,imagem,url,loja,genero,descricao,avaliacao,destaque)
VALUES
(1,'Cyberpunk 2077','cyberpunk-2077','PC / PS5 / Xbox',199.90,79.90,60,'https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg','/gogfake/jogos/cyberpunk-2077.php','GOGFake','RPG / Ação','Explore Night City em uma aventura futurista repleta de escolhas, perigos e personagens marcantes.',9.0,'oferta'),
(2,'Red Dead Redemption 2','red-dead-redemption-2','PC / PS4 / Xbox',249.90,119.90,52,'https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg','/gogfake/jogos/red-dead-redemption-2.php','GOGFake','Ação / Aventura','Viva a saga de Arthur Morgan no crepúsculo do Velho Oeste americano.',9.5,'popular'),
(3,'Hogwarts Legacy','hogwarts-legacy','PC / PS5 / Xbox / Switch',249.90,109.90,56,'https://cdn.cloudflare.steamstatic.com/steam/apps/990080/header.jpg','/gogfake/jogos/hogwarts-legacy.php','GOGFake','RPG / Fantasia','Descubra a magia de Hogwarts em uma jornada original ambientada no mundo bruxo.',8.8,'oferta'),
(4,'Forza Horizon 5','forza-horizon-5','PC / Xbox',249.90,139.90,44,'https://cdn.cloudflare.steamstatic.com/steam/apps/1551360/header.jpg','/gogfake/jogos/forza-horizon-5.php','GOGFake','Corrida','Corra por paisagens vibrantes do México em um festival de velocidade em mundo aberto.',8.9,'lancamento'),
(5,'The Witcher 3: Wild Hunt','the-witcher-3-wild-hunt','PC / PS5 / Xbox / Switch',159.90,39.90,75,'https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg','/gogfake/jogos/the-witcher-3-wild-hunt.php','GOGFake','RPG / Fantasia','Geralt de Rívia enfrenta monstros e intrigas em uma das maiores aventuras medievais dos games.',9.6,'classico'),
(6,'Baldur’s Gate 3','baldurs-gate-3','PC / PS5 / Xbox',249.90,179.90,28,'https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg','/gogfake/jogos/baldurs-gate-3.php','GOGFake','RPG','Monte seu grupo e escreva uma história única em uma aventura de RPG baseada em escolhas.',9.7,'popular'),
(7,'Elden Ring','elden-ring','PC / PS5 / Xbox',249.90,149.90,40,'https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg','/gogfake/jogos/elden-ring.php','GOGFake','RPG / Ação','Atravesse as Terras Intermédias e enfrente desafios lendários em um mundo aberto sombrio.',9.4,'oferta'),
(8,'Grand Theft Auto V','grand-theft-auto-v','PC / PS4 / Xbox',149.90,59.90,60,'https://cdn.cloudflare.steamstatic.com/steam/apps/271590/header.jpg','/gogfake/jogos/grand-theft-auto-v.php','GOGFake','Ação / Mundo aberto','Três criminosos se cruzam em uma história explosiva pelas ruas de Los Santos.',9.2,'classico'),
(9,'Minecraft','minecraft','PC / Console',129.90,89.90,31,'https://images.igdb.com/igdb/image/upload/t_cover_big/co49x5.jpg','/gogfake/jogos/minecraft.php','GOGFake','Aventura / Sandbox','Construa, explore e sobreviva em um universo de possibilidades infinitas.',9.1,'popular'),
(10,'Resident Evil 4','resident-evil-4','PC / PS5 / Xbox',199.90,99.90,50,'https://cdn.cloudflare.steamstatic.com/steam/apps/2050650/header.jpg','/gogfake/jogos/resident-evil-4.php','GOGFake','Terror / Ação','Uma missão de resgate transforma-se em uma luta desesperada pela sobrevivência.',9.0,'oferta'),
(11,'Hades','hades','PC / Switch',99.90,34.90,65,'https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/header.jpg','/gogfake/jogos/hades.php','GOGFake','Ação / Roguelike','Desafie o submundo grego em combates rápidos e uma narrativa que evolui a cada tentativa.',9.3,'classico'),
(12,'Hollow Knight','hollow-knight','PC / PS4 / Xbox / Switch',59.90,19.90,67,'https://cdn.cloudflare.steamstatic.com/steam/apps/367520/header.jpg','/gogfake/jogos/hollow-knight.php','GOGFake','Metroidvania','Explore um reino subterrâneo desenhado à mão, repleto de segredos e criaturas.',9.4,'classico'),
(13,'Stardew Valley','stardew-valley','PC / Console / Mobile',39.90,24.90,38,'https://cdn.cloudflare.steamstatic.com/steam/apps/413150/header.jpg','/gogfake/jogos/stardew-valley.php','GOGFake','Simulação / RPG','Transforme uma fazenda abandonada em um novo lar e faça parte de uma comunidade acolhedora.',9.6,'popular'),
(14,'Sekiro: Shadows Die Twice','sekiro-shadows-die-twice','PC / PS4 / Xbox',229.90,129.90,43,'https://cdn.cloudflare.steamstatic.com/steam/apps/814380/header.jpg','/gogfake/jogos/sekiro-shadows-die-twice.php','GOGFake','Ação / Aventura','Torne-se o Lobo de um braço só e desafie guerreiros em uma jornada de vingança.',9.2,'oferta'),
(15,'Control','control','PC / PS5 / Xbox',149.90,49.90,67,'https://cdn.cloudflare.steamstatic.com/steam/apps/870780/header.jpg','/gogfake/jogos/control.php','GOGFake','Ação / Ficção científica','Domine poderes extraordinários para desvendar os mistérios da Agência Federal de Controle.',8.7,'oferta'),
(16,'Disco Elysium','disco-elysium','PC / PS5 / Xbox / Switch',99.90,29.90,70,'https://cdn.cloudflare.steamstatic.com/steam/apps/632470/header.jpg','/gogfake/jogos/disco-elysium.php','GOGFake','RPG / Investigação','Investigue um assassinato e decida quem você será nesta experiência narrativa incomparável.',9.5,'classico'),
(17,'Doom Eternal','doom-eternal','PC / PS5 / Xbox / Switch',199.90,69.90,65,'https://cdn.cloudflare.steamstatic.com/steam/apps/782330/header.jpg','/gogfake/jogos/doom-eternal.php','GOGFake','Ação / FPS','Atravesse dimensões infernais com um arsenal devastador e combates sem pausa.',9.0,'oferta'),
(18,'Ori and the Will of the Wisps','ori-and-the-will-of-the-wisps','PC / Xbox / Switch',129.90,44.90,65,'https://cdn.cloudflare.steamstatic.com/steam/apps/1057090/header.jpg','/gogfake/jogos/ori-and-the-will-of-the-wisps.php','GOGFake','Plataforma / Aventura','Uma jornada emocionante por uma floresta viva, com plataformas precisas e visuais encantadores.',9.1,'classico'),
(19,'Celeste','celeste','PC / PS4 / Xbox / Switch',59.90,22.90,62,'https://cdn.cloudflare.steamstatic.com/steam/apps/504230/header.jpg','/gogfake/jogos/celeste.php','GOGFake','Plataforma','Ajude Madeline a escalar a montanha Celeste e enfrente seus desafios pessoais.',9.3,'classico'),
(20,'Death Stranding','death-stranding','PC / PS5',199.90,89.90,55,'https://cdn.cloudflare.steamstatic.com/steam/apps/1190460/header.jpg','/gogfake/jogos/death-stranding.php','GOGFake','Aventura / Ação','Reconecte uma América fragmentada em uma experiência cinematográfica e contemplativa.',8.6,'popular'),
(21,'Final Fantasy VII Remake','final-fantasy-vii-remake','PC / PS5',249.90,159.90,36,'https://cdn.cloudflare.steamstatic.com/steam/apps/1462040/header.jpg','/gogfake/jogos/final-fantasy-vii-remake.php','GOGFake','RPG / Ação','Reviva a história de Cloud e Avalanche em uma releitura moderna de um clássico.',9.0,'popular'),
(22,'Persona 5 Royal','persona-5-royal','PC / PS5 / Xbox / Switch',249.90,149.90,40,'https://cdn.cloudflare.steamstatic.com/steam/apps/1687950/header.jpg','/gogfake/jogos/persona-5-royal.php','GOGFake','RPG / JRPG','Leve uma vida dupla e transforme a sociedade ao lado dos Phantom Thieves.',9.6,'oferta'),
(23,'The Last of Us Part I','the-last-of-us-part-i','PC / PS5',249.90,169.90,32,'https://cdn.cloudflare.steamstatic.com/steam/apps/1888930/header.jpg','/gogfake/jogos/the-last-of-us-part-i.php','GOGFake','Ação / Aventura','Atravesse uma América devastada e forme um vínculo inesquecível em uma jornada intensa.',9.0,'popular'),
(24,'Portal 2','portal-2','PC',59.90,14.90,75,'https://cdn.cloudflare.steamstatic.com/steam/apps/620/header.jpg','/gogfake/jogos/portal-2.php','GOGFake','Puzzle / Ficção científica','Use portais, lógica e humor ácido para superar os testes da Aperture Science.',9.7,'classico'),
(25,'Terraria','terraria','PC / Console / Mobile',39.90,17.90,55,'https://cdn.cloudflare.steamstatic.com/steam/apps/105600/header.jpg','/gogfake/jogos/terraria.php','GOGFake','Aventura / Sandbox','Cave, construa e enfrente monstros em um mundo 2D cheio de descobertas.',9.4,'classico'),
(26,'Mass Effect Legendary Edition','mass-effect-legendary-edition','PC / PS4 / Xbox',199.90,79.90,60,'https://cdn.cloudflare.steamstatic.com/steam/apps/1328670/header.jpg','/gogfake/jogos/mass-effect-legendary-edition.php','GOGFake','RPG / Ficção científica','Monte sua equipe e salve a galáxia na trilogia definitiva do Comandante Shepard.',9.2,'oferta'),
(27,'Dragon Age: Inquisition','dragon-age-inquisition','PC / PS4 / Xbox',149.90,54.90,63,'https://cdn.cloudflare.steamstatic.com/steam/apps/1222690/header.jpg','/gogfake/jogos/dragon-age-inquisition.php','GOGFake','RPG / Fantasia','Lidere a Inquisição para fechar uma ruptura que ameaça destruir Thedas.',8.9,'classico'),
(28,'Sifu','sifu','PC / PS5 / Xbox / Switch',149.90,69.90,53,'https://cdn.cloudflare.steamstatic.com/steam/apps/2138710/header.jpg','/gogfake/jogos/sifu.php','GOGFake','Ação / Luta','Domine o kung fu e busque vingança em uma cidade implacável.',8.8,'oferta'),
(29,'Alan Wake 2','alan-wake-2','PC / PS5 / Xbox',229.90,149.90,35,'https://cdn.cloudflare.steamstatic.com/steam/apps/2319300/header.jpg','/gogfake/jogos/alan-wake-2.php','GOGFake','Terror / Aventura','Duas realidades se entrelaçam em um thriller sobrenatural cheio de suspense.',9.0,'lancamento'),
(30,'Bioshock Infinite','bioshock-infinite','PC / PS4 / Xbox',99.90,27.90,72,'https://cdn.cloudflare.steamstatic.com/steam/apps/8870/header.jpg','/gogfake/jogos/bioshock-infinite.php','GOGFake','FPS / Aventura','Viaje à cidade flutuante de Columbia em uma narrativa de ficção científica memorável.',9.1,'classico');
